Диплом stat_svc 1.0
Jiv4ii/java-explore-with-me pull request #1
Opened 2024-01-19 02:53 UTC by Jiv4ii

2024-01-20 16:42 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-01-20 16:42 UTC, LexLippi commented on ewm-service/src/main/java/ru/practicum/ewmservice/controller/MainServiceController.java
> +}
1. Это зачем?)
2. Это вообще не соответствует названию метода

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS hits CASCADE;
Такое не стоит оставлять в финальной версии

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/resources/schema.sql
> +                                    ip VARCHAR NOT NULL,
Таким полям стоит проставить ограничение на размер сверху

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/resources/schema.sql
> +                                    created TIMESTAMP NOT NULL
А нужна ли нам здесь `timezone`? Или можно `timestamp without timezone`?

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/service/HitService.java
> +        if (uris.isEmpty() && unique) {
Во второй части условия нет необходимости, так как если список пустой, то единственный оставшийся вариант, что `unique == true`

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/service/HitService.java
> +//        LocalDateTime end = LocalDateTime.parse(strEnd, formatter);
Это стоит удалить

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/service/HitService.java
> +public class HitService {
Сервис не должен знать ни про какие `ResponseEntity`, так как в этом его смысл. Его может вызывать консольная утилита и мы должны получать корректный ответ

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/service/HitService.java
> +    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
Это лучше сделать константой проекта (завести под это дело отдельный класс)

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/repository/HitRepository.java
> +            "order by count (h.ip) desc")
`distinct` не хватает

2024-01-20 16:42 UTC, LexLippi commented on stats-server/http-server/src/main/java/ru/practicum/repository/HitRepository.java
> +            "order by count (h.ip) desc")
`distinct`

2024-01-21 15:38 UTC, Jiv4ii commented on stats-server/http-server/src/main/resources/schema.sql
> +                                    created TIMESTAMP NOT NULL
Можно, можно

2024-01-22 07:22 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи на следующих этапах диплома!

2024-01-29 22:37 UTC, merged